site_name: Gustavo de Moura
site_url: https://gustavo-moura.github.io/gustavo-moura/
site_description: Personal website.
site_author: Gustavo de Moura
repo_url: https://github.com/gustavo-moura

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  font:
    text: Funnel Display
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    # - navigation.sections
    - navigation.instant
    # - announce.dismiss
    # - header.autohide
    - navigation.indexes

plugins:
  - blog:
      archive: true
      blog_toc: false
      post_date_format: long

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gustavo-moura
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/gustavo-moura
  generator: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - About Me: about_me.md
  - Blog:
    - blog/index.md
  - Publications: publications.md
  - Games: games.md
  - Resources: resources.md
